/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JLin
 */
public class pagamento extends javax.swing.JFrame {

    /**
     * Creates new form pagamento
     */
    public pagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPagamento = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cbxTotal = new javax.swing.JCheckBox();
        btnDebito = new javax.swing.JButton();
        btnDinheiro = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblPagamento.setText("Pagamento");
        getContentPane().add(lblPagamento);
        lblPagamento.setBounds(10, 10, 120, 30);

        lblValor.setText("VALOR");
        getContentPane().add(lblValor);
        lblValor.setBounds(70, 60, 60, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 60, 140, 40);

        cbxTotal.setText("TOTAL");
        cbxTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTotalActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTotal);
        cbxTotal.setBounds(290, 70, 81, 23);

        btnDebito.setText("D");
        getContentPane().add(btnDebito);
        btnDebito.setBounds(270, 140, 73, 70);

        btnDinheiro.setText("DN");
        getContentPane().add(btnDinheiro);
        btnDinheiro.setBounds(70, 140, 70, 70);

        btnCredito.setText("C");
        getContentPane().add(btnCredito);
        btnCredito.setBounds(170, 140, 73, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCredito;
    private javax.swing.JButton btnDebito;
    private javax.swing.JButton btnDinheiro;
    private javax.swing.JCheckBox cbxTotal;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
